### ISSUE TITLE
Codeql Cli does not close the issues reported by codeql runner

### ISSUE THREAD

**Issue by avaria-ias** [github/codeql-cli-binaries#106]
Hello Team, 

Since the codeql runner is deprecated, moved to cli. But the old findings reported by runner, which are now fixed, but it is not getting closed by cli. 

Is there any way this could be done?

**Comment by adityasharad** [comment]
Could you please share the command lines you are using to call the Runner and the CLI? In particular, were you using an analysis "category" in either command?

**Comment by avaria-ias** [comment]
Runner commands : 
echo "${CODEQL_GITHUB_TOKEN}" | /usr/local/bin/codeql-runner init --repository <repo_url> --github-url https://github.com --config-file <repo>/.github/codeql/codeql-config.yml@master --codeql-path ${CODEQL_PATH} %s --github-auth-stdin
                |echo "${CODEQL_GITHUB_TOKEN}" | /usr/local/bin/codeql-runner init --repository integralads/${JERVIS_PROJECT} --github-url https://github.com --config-file ${WORKSPACE}/.github/codeql/codeql-config.yml --codeql-path ${CODEQL_PATH} %s --github-auth-stdin

Cli commands:

codeql database create "\\${WORKSPACE}"/codeql_databases/ --db-cluster --language=${languages} ${buildSteps} --source-root="\\${WORKSPACE}" --codescanning-config="\\${WORKSPACE}"/.github/codeql/codeql-config.yml --no-run-unnecessary-builds --overwrite

|codeql database analyze "\\${WORKSPACE}"/codeql_databases/${language} --format=sarif-latest --sarif-category=${language} --output="\\${WORKSPACE}"/${language}-results.sarif 
|echo "\\${CODEQL_GITHUB_TOKEN}" | codeql github upload-results --repository=integralads/"\\${WORKSPACE}" --commit="\\$(COMMIT)" --ref=${reference} --sarif="\\${WORKSPACE}"/${language}-results.sarif --github-auth-stdin

Also, no i have not used any category in specific? could you share some more details about it. 

One thing i want to point it out that for the runner the query was "security-and-quality"(under queries secton) and for the cli it is security only, if that makes any difference.

**Comment by avaria-ias** [comment]
@adityasharad : Any update on the above issue?

**Comment by adityasharad** [comment]
Thanks for sharing your command lines. There are a couple of differences that could cause the mismatch here:
- Analysis categories (see [docs here](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#configuring-a-category-for-the-analysis)). Categories help distinguish multiple analyses from the same tool and commit, e.g. for different languages. Alerts are only matched within the same category.
  - The CodeQL CLI command line you shared uses `codeql database analyze ... --sarif-category=${language}`. This sets the language name as the category.
  - I don't see the command line where you called `codeql-runner analyze`, but please check whether there was a `--category` option passed to it. The two categories need to match for the old and new alerts to be matched up.
- Running a different set of queries.
  - It is relevant that you were running `security-and-quality` with the Runner and only the default query suite with the CLI. Thanks for mentioning that.
  - The default suite is smaller than `security-and-quality`. This means that if you have old alerts produced by queries that are in `security-and-quality` but that are not included in the default suite, those old alerts will not be closed automatically by your new runs. (This is by design: those alerts weren't actually fixed.) You have two options:
    - Change the `codeql database analyze` command line to run the `${language}-security-and-quality.qls` query suite. Then you will be running the same set of queries.
    - Manually close the alerts _only_ for the queries that you are no longer running. They will not appear again, since you're not running those queries again.
    - If you have trouble with this, please share the names/IDs of the queries that produced the alerts that you're unable to close.

**Comment by avaria-ias** [comment]
@adityasharad : While i am checking on the resolving the issues and mentioned suggestion above. I have one question for the cli. 
1. Do we have any option we can export the CSV for that scanning analysis ?.. As per docs, it is only limited to the individual query itself. Can we have it for whole analysis ?

**Comment by adityasharad** [comment]
If you'd like the analysis results in CSV format, try running something like `codeql database analyze --format=csv --output="\${WORKSPACE}"/${language}-results.csv <other args>` ([docs here](https://codeql.github.com/docs/codeql-cli/analyzing-databases-with-the-codeql-cli/))

That will produce a CSV file instead of SARIF (which is a JSON format).
You may also find the SARIF file useful -- that is a JSON file containing a detailed representation of the entire set of analysis results. It is more complex to read but is slightly easier to automatically process than CSV. 

Note you will still need to produce SARIF to upload code scanning results to GitHub. So if you want to produce both SARIF and CSV, run both variations of the command, one after the other. The CodeQL analysis results will be found on disk so it won't rerun the entire analysis the second time.
