### ISSUE TITLE
database analyze interrupted

### ISSUE THREAD

**Issue by mvanotti** [github/codeql-cli-binaries#15]
I tried to run the full lgtm query suite in a big project, and after a few days, I tried to see if it finished, but found the following message:

```
Starting evaluation of codeql-cpp/Likely Bugs/Underspecified Functions/ImplicitFunctionDeclaration.ql.
Starting evaluation of codeql-cpp/Likely Bugs/Likely Typos/UsingStrcpyAsBoolean.ql.
Starting evaluation of codeql-cpp/Security/CWE/CWE-131/NoSpaceForZeroTerminator.ql.
Starting evaluation of codeql-cpp/Likely Bugs/Memory Management/ReturnCstrOfLocalStdString.ql.
Starting evaluation of codeql-cpp/Critical/NewArrayDeleteMismatch.ql.
Starting evaluation of codeql-cpp/Likely Bugs/Memory Management/ReturnStackAllocatedMemory.ql.
Starting evaluation of codeql-cpp/Likely Bugs/Memory Management/AllocaInLoop.ql.
Starting evaluation of codeql-cpp/Security/CWE/CWE-120/BadlyBoundedWrite.ql.
Starting evaluation of codeql-cpp/Likely Bugs/Likely Typos/inconsistentLoopDirection.ql.
Starting evaluation of codeql-cpp/Critical/NewFreeMismatch.ql.
Starting evaluation of codeql-cpp/Critical/OverflowStatic.ql.
Starting evaluation of codeql-cpp/Critical/NewDeleteArrayMismatch.ql.
Starting evaluation of codeql-cpp/Security/CWE/CWE-120/OverrunWrite.ql.
Starting evaluation of codeql-cpp/Likely Bugs/Conversion/LossyFunctionResultCast.ql.
Starting evaluation of codeql-cpp/Security/CWE/CWE-120/OverrunWriteFloat.ql.
[1/15] Evaluation done (1m48s); writing results to codeql-cpp/Likely Bugs/Underspecified Functions/ImplicitFunctionDeclaration.bqrs.
  

Shutting down query evaluator.
Interpreting results.
codeql-home/ql/cpp/ql/src/Likely Bugs/Likely Typos/UsingStrcpyAsBoolean.ql ought to have produced codeql-home/fuchsia-ql/results/codeql-cpp/Likely 
Bugs/Likely Typos/UsingStrcpyAsBoolean.bqrs but that doesn't exist -- ignoring.
```

There's one message per each of the ql queries that didn't finish.

It looks like the query evaluator got interrupted after ~2 days (maybe a timeout?). I couldn't find anything in the cmdline reference that could cause the process to finish.

I am re-running the command with -vvvvv to see if there's something else going on.

**Comment by mvanotti** [comment]
[Here's](https://gist.githubusercontent.com/mvanotti/c480e5cda5f2ec4b8c7b5338dfcb6338/raw/71d24797e60e5fd555b2e7798d64ada3b278ff36/codeql-database-analyze-output.log) the full log (minus the "Recursing into... " lines, there were ~400k of those).

**Comment by p0** [comment]
The error-reporting here is quite unhelpful. Ultimately, the issue is that we have a built-in 24h timeout on query evaluation (for historic reasons). Obviously that needs to be relaxed to analyze particularly large databases.

We'll look into making the timeout configurable in future releases; I'm afraid until then there isn't a good workaround...

**Comment by mvanotti** [comment]
Hi Pavel, thanks for the answer.

Is there any command line parameter that would make these queries run faster?

**Comment by p0** [comment]
We’ve identified a potential performance bottleneck on our Fuchsia build that probably explains the long query times here, and are investigating a fix. If the problem for you is the same, then unfortunately the problem is a single long-running computation which can’t be easily sped up through options you provide.

In general, providing more RAM and threads to CodeQL will make queries execute faster, up to a point and depending on the database.

**Comment by hmakholm** [comment]
Starting at last week's release version 2.0.4 of the CLI, there is no timeout by default, but instead a `--timeout` command-line option that can be used to set a timeout explicitly. Not sure whether there is more to say about the performance bottleneck @p0 mentioned, but unassigning myself.

**Comment by p0** [comment]
Closing this issue; we're tracking the unrelated performance fixes separately.
