### ISSUE TITLE
`query compile --check-only` is rather slow

### ISSUE THREAD

**Issue by Marcono1234** [github/codeql-cli-binaries#55]
I am currently looking for a CodeQL CLI command for a GitHub workflow to verify that queries can be compiled (but I don't want to run the queries).
The command [`query compile --check-only`](https://codeql.github.com/docs/codeql-cli/manual/query-compile/#cmdoption-codeql-query-compile-n) seems to be well suited for this, however it appears to be rather slow.
For example for a GitHub workflow runner compiling a query takes on average 1.8 seconds (see [workflow run](https://github.com/Marcono1234/codeql-java-queries/runs/2153223315#check-step-7)); running CodeQL CLI locally even takes 4s on average for me. (Note also that using a more specific `.codeqlmanifest.json` file which explicitly lists the query pack files instead of using `**` is not much faster.)
Given that the CodeQL VSCode extension is able to check whether a query has any compilation errors and report them in less than a second, I was wondering whether `query compile --check-only` might actually be doing more than I need (or more than the documentation "Just check that the QL is valid and print any errors" describes). Am I using the command incorrectly?

A workaround might be to misuse `query format`'s ability to check syntax. However, this has the disadvantages that it only works for one file at a time (and not recursively for a directory), and that it really only checks syntax; it won't report any compilation errors such as wrong imports or missing types.

**Comment by dbartol** [comment]
There are a few reasons why `codeql query compile --check-only` takes a bit longer than the language server in the VS Code extension does:

First, the extension skips some expensive checks to make the response time for the error squigglies better. Some of the checks that a real QL compilation does require analyzing the entire query, including all of its dependencies, as a whole program. The extension skips these checks so that it can mostly check each QL source file independently. So, `codeql query compile --check-only` really is doing more work, and will report errors that you would not see in the extension.

Second, the extension has a bit of a head start, because it uses a server process that has already paid the cost of JVM startup, which can be fairly significant for compilations that only take a few seconds.

Finally, compilation requires a fair bit of RAM, and the default amount of RAM available to the JVM is something like 25% of the total RAM of the machine. If you're using the default Actions runner, that's less than 2GB of RAM to the JVM. Adding a `--ram 6144` switch to the `codeql query compile` command line might speed things up a bit.

So, I'd suggest that you keep using `codeql query compile --check-only`, but see if the `--ram` switch speed things up a bit.

**Comment by Marcono1234** [comment]
Thanks for the insight and the tips.

> cost of JVM startup, which can be fairly significant for compilations that only take a few seconds

That might explain then why the compilation of the first query takes on average twice as long as the other queries. However, it looks like when a directory is passed to `query compile` the same JVM session is used for all queries, so I cannot speed up the workflow here then.

Tweaking the `--ram` or `--threads` value might have slightly improved the performance but it is difficult to tell. For example during testing I just got a ['super fast' run](https://github.com/Marcono1234/codeql-java-queries/runs/2179926258#check-step-7) with a GitHub runner where every query only took about 1.5 seconds on average without tweaking `--ram` or `--threads` at all.
From a brief glimpse with VisualVM at the CodeQL CLI process it did not look like memory consumption was an issue though.

After all this is still complaining at a high level; 4 minutes for compiling all the queries is still pretty decent. I guess I will use that approach then and only come back to you if I really notice bad performance.
Sorry for bothering you; I will close this issue then.

**Comment by Marcono1234** [comment]
It looks like you can speed this up by not using `--check-only`, but instead having CodeQL CLI compile the queries (possibly with `--fast-compilation`) and then cache the compilation cache directory (`.cache`), for example using the [GitHub cache action](https://github.com/actions/cache). The first execution then takes a bit longer than before, but subsequent runs only need to compile the queries again when they (or their imported library files) changed.
