### ISSUE TITLE
How to submit queries to cli-server

### ISSUE THREAD

**Issue by Sebastian1011** [github/codeql-cli-binaries#96]
I want to run multi  query command. It seems that cli-server can solve my problem. 
But after reading the docs (https://codeql.github.com/docs/codeql-cli/manual/execute-cli-server/),
I'm confused about how to run a query with the server which started with the command '$ codeql execute cli-server'.

**Comment by aeisenberg** [comment]
The cli server is really meant for interactivity inside of an IDE in order to avoid the JVM startup cost when executing multiple commands. Even though it's available, it's not really meant for external consumption. You can see how it is used inside of the vscode-codeql extension:

https://github.com/github/vscode-codeql/blob/3743895b66f0bf14b4014cba96d0596e9ecb730f/extensions/ql-vscode/src/cli.ts#L283-L353

Essentially, after you start the server, you can send utf8 text to the server via stdin. You need to separate commands by sending a null byte `\0`. Similarly, you can listen for responses on stdout as utf8, separated by a null byte. The server cannot handle multiple commands in parallel.

The cli server is not recommended for running queries. For that, you should run the `execute query-server` command, which _does_ allow multiple queries running in parallel (as long as they are on the same database).

I'm interested to hear your use case.

**Comment by hmakholm** [comment]
And if all you want is to evaluate multiple queries against the same database, and you know in advance which queries they are, `codeql database run-queries` is more convenient than `database execute query-server`.

**Comment by Sebastian1011** [comment]
>

**Comment by Sebastian1011** [comment]
> The cli server is really meant for interactivity inside of an IDE in order to avoid the JVM startup cost when executing multiple commands. Even though it's available, it's not really meant for external consumption. You can see how it is used inside of the vscode-codeql extension:
> 
> https://github.com/github/vscode-codeql/blob/3743895b66f0bf14b4014cba96d0596e9ecb730f/extensions/ql-vscode/src/cli.ts#L283-L353
> 
> Essentially, after you start the server, you can send utf8 text to the server via stdin. You need to separate commands by sending a null byte `\0`. Similarly, you can listen for responses on stdout as utf8, separated by a null byte. The server cannot handle multiple commands in parallel.
> 
> The cli server is not recommended for running queries. For that, you should run the `execute query-server` command, which _does_ allow multiple queries running in parallel (as long as they are on the same database).
> 
> I'm interested to hear your use case.

Got it. Thank you very much.
